import React from 'react';

function Login() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="720"
      height="520"
      fill="none"
      viewBox="0 0 720 520"
    >
      <g clipPath="url(#clip0_45_21806)">
        <path fill="#fff" d="M0 0H720V520H0z"></path>
        <g opacity="0.4">
          <rect width="97" height="97" x="-28" fill="url(#paint0_linear_45_21806)" rx="12"></rect>
          <rect
            width="95"
            height="95"
            x="-27"
            y="1"
            stroke="#9FE870"
            strokeOpacity="0.5"
            strokeWidth="2"
            rx="11"
          ></rect>
          <rect
            width="96"
            height="96"
            x="69.5"
            y="0.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="96"
            height="96"
            x="166.5"
            y="0.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="96"
            height="96"
            x="263.5"
            y="0.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect width="97" height="97" x="360" fill="url(#paint1_linear_45_21806)" rx="12"></rect>
          <rect
            width="95"
            height="95"
            x="361"
            y="1"
            stroke="#9FE870"
            strokeOpacity="0.5"
            strokeWidth="2"
            rx="11"
          ></rect>
          <rect
            width="96"
            height="96"
            x="457.5"
            y="0.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="96"
            height="96"
            x="554.5"
            y="0.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="96"
            height="96"
            x="651.5"
            y="0.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="96"
            height="96"
            x="-27.5"
            y="97.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="96"
            height="96"
            x="69.5"
            y="97.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="97"
            height="97"
            x="166"
            y="97"
            fill="url(#paint2_linear_45_21806)"
            rx="12"
          ></rect>
          <rect
            width="95"
            height="95"
            x="167"
            y="98"
            stroke="#9FE870"
            strokeOpacity="0.5"
            strokeWidth="2"
            rx="11"
          ></rect>
          <rect
            width="96"
            height="96"
            x="263.5"
            y="97.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="96"
            height="96"
            x="360.5"
            y="97.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="96"
            height="96"
            x="457.5"
            y="97.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="96"
            height="96"
            x="554.5"
            y="97.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="96"
            height="96"
            x="651.5"
            y="97.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="96"
            height="96"
            x="-27.5"
            y="194.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="96"
            height="96"
            x="69.5"
            y="194.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="96"
            height="96"
            x="166.5"
            y="194.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="96"
            height="96"
            x="263.5"
            y="194.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="96"
            height="96"
            x="360.5"
            y="194.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="97"
            height="97"
            x="457"
            y="194"
            fill="url(#paint3_linear_45_21806)"
            rx="12"
          ></rect>
          <rect
            width="95"
            height="95"
            x="458"
            y="195"
            stroke="#9FE870"
            strokeOpacity="0.5"
            strokeWidth="2"
            rx="11"
          ></rect>
          <rect
            width="96"
            height="96"
            x="554.5"
            y="194.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="96"
            height="96"
            x="651.5"
            y="194.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="96"
            height="96"
            x="-27.5"
            y="291.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="96"
            height="96"
            x="69.5"
            y="291.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="97"
            height="97"
            x="166"
            y="291"
            fill="url(#paint4_linear_45_21806)"
            rx="12"
          ></rect>
          <rect
            width="95"
            height="95"
            x="167"
            y="292"
            stroke="#9FE870"
            strokeOpacity="0.5"
            strokeWidth="2"
            rx="11"
          ></rect>
          <rect
            width="96"
            height="96"
            x="263.5"
            y="291.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="96"
            height="96"
            x="360.5"
            y="291.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="96"
            height="96"
            x="457.5"
            y="291.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="96"
            height="96"
            x="554.5"
            y="291.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
          <rect
            width="96"
            height="96"
            x="651.5"
            y="291.5"
            fill="#fff"
            stroke="#E5E5E5"
            rx="11.5"
          ></rect>
        </g>
        <path fill="url(#paint5_radial_45_21806)" d="M0 0H720V520H0z"></path>
      </g>
      <defs>
        <linearGradient
          id="paint0_linear_45_21806"
          x1="20.5"
          x2="20.5"
          y1="0"
          y2="97"
          gradientUnits="userSpaceOnUse"
        >
          <stop stopColor="#9FE870" stopOpacity="0.25"></stop>
          <stop offset="1" stopColor="#fff" stopOpacity="0"></stop>
        </linearGradient>
        <linearGradient
          id="paint1_linear_45_21806"
          x1="408.5"
          x2="408.5"
          y1="0"
          y2="97"
          gradientUnits="userSpaceOnUse"
        >
          <stop stopColor="#9FE870" stopOpacity="0.25"></stop>
          <stop offset="1" stopColor="#fff" stopOpacity="0"></stop>
        </linearGradient>
        <linearGradient
          id="paint2_linear_45_21806"
          x1="214.5"
          x2="214.5"
          y1="97"
          y2="194"
          gradientUnits="userSpaceOnUse"
        >
          <stop stopColor="#9FE870" stopOpacity="0.25"></stop>
          <stop offset="1" stopColor="#fff" stopOpacity="0"></stop>
        </linearGradient>
        <linearGradient
          id="paint3_linear_45_21806"
          x1="505.5"
          x2="505.5"
          y1="194"
          y2="291"
          gradientUnits="userSpaceOnUse"
        >
          <stop stopColor="#9FE870" stopOpacity="0.25"></stop>
          <stop offset="1" stopColor="#fff" stopOpacity="0"></stop>
        </linearGradient>
        <linearGradient
          id="paint4_linear_45_21806"
          x1="214.5"
          x2="214.5"
          y1="291"
          y2="388"
          gradientUnits="userSpaceOnUse"
        >
          <stop stopColor="#9FE870" stopOpacity="0.25"></stop>
          <stop offset="1" stopColor="#fff" stopOpacity="0"></stop>
        </linearGradient>
        <radialGradient
          id="paint5_radial_45_21806"
          cx="0"
          cy="0"
          r="1"
          gradientTransform="matrix(0 371 -513.692 0 360 149)"
          gradientUnits="userSpaceOnUse"
        >
          <stop stopColor="#fff" stopOpacity="0"></stop>
          <stop offset="0.46" stopColor="#fff"></stop>
        </radialGradient>
        <clipPath id="clip0_45_21806">
          <path fill="#fff" d="M0 0H720V520H0z"></path>
        </clipPath>
      </defs>
    </svg>
  );
}

export default Login;
